package com.baijiayun.lib_compiler;

import java.io.IOException;
import java.io.Writer;
import java.util.Collection;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;
import javax.tools.JavaFileObject;

/**
 * @author DSG
 * @Project PushPlugin-master
 * @date 2019-08-26
 * @describe
 */
@SupportedAnnotationTypes("com.baijiayun.lib_compiler.GenerateEntry")
@SupportedSourceVersion(SourceVersion.RELEASE_8)
public class WxAnnotationProcessor extends AbstractProcessor {
    @Override
    public boolean process(Set<? extends TypeElement> set, RoundEnvironment roundEnv) {
        // 1.获取类型信息
        System.out.println("1111111111");
        Collection<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(GenerateEntry.class);
        List<TypeElement> types = ElementFilter.typesIn(annotatedElements);
        String packageName = null;
        String appId = null;

        for (TypeElement type : types) {
            PackageElement packageElement = (PackageElement) type.getEnclosingElement();
            packageName = packageElement.getQualifiedName().toString();
            appId = type.getAnnotation(GenerateEntry.class).appId();
        }

        if (packageName == null) return false;
        if (!appId.equalsIgnoreCase("")) {
            packageName = appId;
        }

        // 3.生成Java源文件
        try {
            JavaFileObject javaFileObject = processingEnv.getFiler().createSourceFile(packageName + ".wxapi.WXEntryActivity");
            Writer writer = javaFileObject.openWriter();
            writer.write(brewCode(packageName));
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return false;
    }

    private String brewCode(String pkName) {

        // 2.构造Java代码
        return "package " + pkName + ".wxapi;\n\n" +
                "import android.content.Intent;\n" +
                "import android.os.Bundle;\n" +
                "import cn.jiguang.share.wechat.WeChatHandleActivity;\n" +
                "/** 微信客户端回调activity示例 */\n" +
                "/** DO NOT EDIT THIS FILE!!! IT WAS AUTOMATICALLY GENERATED */\n" +
                "public class WXEntryActivity extends WeChatHandleActivity {\n" +
                " @Override\n" +
                "protected void onCreate(Bundle savedInstanceState) {\n" +
                "        super.onCreate(savedInstanceState);\n" +
                "    }\n" +
                "    @Override\n" +
                "    protected void onNewIntent(Intent intent) {\n" +
                "        super.onNewIntent(intent);\n" +
                "    }\n" +
                "}\n";
    }


}
